services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: backend_image
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - elasticsearch
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=videos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es-multilingual
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  minio_data:
  esdata:
