services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: backend_image
    volumes:
      - ../backend:/app
      - /tmp/videos:/tmp/videos
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - elasticsearch
    env_file:
      - .env

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: worker_image
    volumes:
      - ../backend:/app
      - /tmp/videos:/tmp/videos
    depends_on:
      - backend
      - db
      - redis
      - minio
      - elasticsearch
    env_file:
      - .env
    command: celery -A worker.celery_app worker --loglevel=info

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Консоль
    volumes:
      - minio_data:/data

  elasticsearch:
    build:
      context: ..
      dockerfile: docker/Dockerfile.elastic
    image: elasticsearch_image
    container_name: es-multilingual
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  minio_data:
  esdata:
