services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: backend_image
    volumes:
      - ../backend:/app
      - /tmp/videos:/tmp/videos
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
      - elasticsearch
    env_file:
      - .env

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: worker_image
    volumes:
      - ../backend:/app
      - /tmp/videos:/tmp/videos  # Монтирование той же директории для временных файлов
    depends_on:
      - backend
      - db
      - redis
      - minio
      - elasticsearch
    environment:
      PROGRAM_NAME: ${PROGRAM_NAME}
      PROGRAM_VERSION: ${PROGRAM_VERSION}
      TIMEZONE: ${TIMEZONE}
      API_V1_STR: ${API_V1_STR}
      HOST: ${HOST}
      PORT: ${PORT}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_DB: ${POSTGRES_DB}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_INDEX_NAME: ${ELASTICSEARCH_INDEX_NAME}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      TEMP_UPLOAD_DIR: ${TEMP_UPLOAD_DIR}
    command: celery -A tasks.celery_app worker --loglevel=info

  flower:
    image: mher/flower:latest
    command: flower --broker=${CELERY_BROKER_URL} --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Консоль
    volumes:
      - minio_data:/data

  elasticsearch:
    build:
      context: ..
      dockerfile: docker/Dockerfile.elastic
    image: elasticsearch_image
    container_name: es-multilingual
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  minio_data:
  esdata:
